services:
  # Conteneur recepteur
  api-recepteur:
    build: .
    env_file: .env
    volumes:
      - ./src:/app/src
    command: ["uv" ,"run", "uvicorn" ,"src.API.streamrecepteur:app", "--host", "0.0.0.0" , "--port", "8000"]
    ports:
      - "${API_PORT}:${API_PORT}"

  # conteneur envoi
  stream-envoi:
    build: .
    environment:
      - API_URL=http://api-recepteur:8000
    env_file: .env
    depends_on:
      - api-recepteur
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    command: ["uv", "run", "python", "src/API/streamenvoi.py"]


  # streamlit
  dashboard:
    build: .
    env_file: .env
    depends_on:
      - api-recepteur
    environment:
      - API_URL=http://api-recepteur:8000
    command: ["uv" ,"run","streamlit", "run", "src/dashboard/dashboard.py", "--server.address", "0.0.0.0"]
    volumes:
      - ./src:/app/src
    ports:
      - "${DASHBOARD_PORT}:${DASHBOARD_PORT}"
