name: projet_fraude_cb

services:
  # conteneur recepteur
  api-recepteur:
    container_name: apirecepteur
    build: .
    env_file: .env
    networks:
      pynet:
        ipv4_address: 172.20.0.2
    volumes:
      - ./src:/app/src
    depends_on:
      - redis  # on évite que l'API plante si le conteneur redis n'est pas encore prêt
    command: ["uv" ,"run", "uvicorn" ,"src.API.streamrecepteur:app", "--host", "0.0.0.0" , "--port", "8000"]
    ports:
      - "${API_PORT}:8000"

  # conteneur envoi
  stream-envoi:
    container_name: streamenvoi
    build: .
    environment:
      - API_URL=http://api-recepteur:8000
    env_file: .env
    depends_on:
      - api-recepteur
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    command: ["uv", "run", "python", "src/API/streamenvoi.py"]
    networks:
      pynet:
        ipv4_address: 172.20.0.3

  # retrain automatisation
  retrain-automation:
    container_name: retrain-automation
    build: .
    env_file: .env
    depends_on:
      - api-recepteur
      - prefect-server
    networks:
      pynet:
        ipv4_address: 172.20.0.10
    volumes:
      - ./src:/app/src
      - ./state.json:/app/state.json
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    command: ["uv", "run", "python", "src/retrain/retrain.py"]

  # conteneur prefect server
  prefect-server:
    image: prefecthq/prefect:3-python3.12
    container_name: prefect-server
    restart: always
    volumes:
      - prefect_data:/root/.prefect
    entrypoint: ["prefect", "server", "start"]
    environment:
      - PREFECT_UI_ENABLED=true
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_URL=${BASE_URL}:${PRF_PORT}/api
    ports:
      - "${PRF_PORT}:4200"
    networks:
      pynet:
        ipv4_address: 172.20.0.12

  # streamlit
  dashboard:
    container_name: dashboard
    build: .
    env_file: .env
    depends_on:
      - api-recepteur
    networks:
      pynet:
        ipv4_address: 172.20.0.4
    environment:
      - API_URL=http://api-recepteur:8000
    command: ["uv", "run", "streamlit", "run", "src/dashboard/dashboard.py", "--server.address", "0.0.0.0", "--server.runOnSave", "true"]
    volumes:
      - ./src:/app/src
      - ./images:/app/images
      - ./.streamlit:/app/.streamlit
      - ./state.json:/app/state.json
    ports:
      - "${DASHBOARD_PORT}:8501"

  # promotheus, grafana et cadvisor pour le monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PRM_PORT}:9090"
    restart: unless-stopped #prometheus restarts automatically if it crashes or the system reboots
    env_file: .env
    networks:
      pynet:
        ipv4_address: 172.20.0.5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file: .env
    ports:
      - "${GF_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      #- grafana-storage:/var/lib/grafana
      # On injecte les fichiers de config
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      # On injecte le fichier JSON du dashboard
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
    networks:
      pynet:
        ipv4_address: 172.20.0.6

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "${CAD_PORT}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      pynet:
        ipv4_address: 172.20.0.7
    env_file: .env

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "${NODE_PORT}:9100"
    networks:
      pynet:
        ipv4_address: 172.20.0.11
    env_file: .env

  # conteneur redis
  redis:
    image: redis:latest             # téléchargement de l'image officielle 
    container_name: redis-service
    networks:
      pynet:
        ipv4_address: 172.20.0.8
    env_file: .env
    ports:
      - "${REDIS_PORT}:6379"
    command: --port ${REDIS_PORT}
    volumes:        
      - redis_data:/data        


  # conteneur worker BigQuery
  worker-bigquery:
    build: . #/api-recepteur
    container_name: worker-bigquery
    command: python src/API/worker_bq.py
    env_file: .env
    depends_on:
      - redis
    networks:
      pynet:
        ipv4_address: 172.20.0.9
    environment:
      - REDIS_HOST=redis-service

volumes:
  redis_data:
  prefect_data:

networks:
  pynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
